import { useMemo, useState } from "react";
import { Activity, BarChart3, BellRing, CalendarCheck, CheckCircle2, ChevronDown, Download, Ellipsis, FileText, Filter, Grid2X2, LockKeyhole, Plus, Search, Settings, ShieldCheck, SlidersHorizontal, Star, Users, Wrench, XCircle } from "lucide-react";
import Profile from "./Profile";

const maroon = "#a90920";
const navigation = [
  ["dashboard", "Dashboard", Grid2X2], ["reports", "Reports", FileText], ["team", "Team", Users], ["analytics", "Analytics", BarChart3], ["settings", "Settings", Settings], ["profile", "Profile", Users],
];
const reportRows = [
  { id: "#REP-1024", title: "Broken Elevator", place: "DPT Block B, Level 4", category: "Electrical", time: "Today · 10:24 AM", priority: "Urgent", status: "Pending", tone: "red" },
  { id: "#REP-1023", title: "Water Leak - Ceiling", place: "Science Lab 302, North Wing", category: "Plumbing", time: "Today · 09:15 AM", priority: "Normal", status: "In Progress", tone: "blue" },
  { id: "#REP-1021", title: "HVAC Filter Replacement", place: "Auditorium Main Hall", category: "AC/Heat", time: "Yesterday · 04:45 PM", priority: "Normal", status: "Resolved", tone: "green" },
  { id: "#REP-1019", title: "Graffiti on West Wall", place: "Campus Perimeter Fence", category: "Cleaning", time: "Oct 24, 2023 · 11:00 AM", priority: "Low", status: "Resolved", tone: "green" },
  { id: "#REP-1015", title: "Main Pipe Burst", place: "Science Annex Quad", category: "Plumbing", time: "Oct 23, 2023 · 02:30 PM", priority: "Urgent", status: "In Progress", tone: "blue" },
];
const team = [
  ["Marcus Sterling", "marcus.s@facility.com", "Lead Electrician", "Active Now", "#REP-1024 - Broken Elevator", "4.9", "MS"],
  ["Sarah Jenkins", "s.jenkins@facility.com", "Senior Plumber", "On Break", "Available in 15m", "4.8", "SJ"],
  ["James Wu", "j.wu@facility.com", "HVAC Specialist", "Active Now", "#REP-1021 - Filter Change", "4.7", "JW"],
  ["Robert Chen", "r.chen@facility.com", "General Maintenance", "Offline", "Shift ends 5:00 PM", "4.5", "RC"],
  ["Elena Rodriguez", "elena.r@facility.com", "Cleaning Lead", "Active Now", "#REP-1019 - Graffiti Removal", "5.0", "ER"],
];

function ActionButton({ children, secondary = false, onClick }) { return <button onClick={onClick} className={`admin-action ${secondary ? "admin-action-secondary" : ""}`}>{children}</button>; }
function Badge({ children, tone = "slate" }) { return <span className={`admin-badge admin-badge-${tone}`}>{children}</span>; }
function Status({ children }) { const tone = children === "Pending" ? "red" : children === "In Progress" ? "blue" : "green"; return <span className={`admin-status admin-status-${tone}`}><i />{children}</span>; }

function AdminSidebar({ page, onPage }) { return <aside className="admin-sidebar"><div className="admin-sidebar-brand"><span><Grid2X2 /></span><b>AdminPanel</b></div><nav>{navigation.map(([key, label, Icon]) => <button key={key} onClick={() => onPage(key)} className={page === key ? "active" : ""}><Icon />{label}</button>)}</nav><div className="admin-user"><span>AS</span><div><b>Admin User</b><small>Facilities Lead</small></div></div></aside>; }
function AdminHeader({ title, subtitle, children }) { return <header className="admin-header"><div><h1>{title}</h1><p>{subtitle}</p></div><div className="admin-header-actions">{children}</div></header>; }
function StatCard({ label, value, detail, tone = "green" }) { return <article className="admin-stat"><span>{label}</span><div><b>{value}</b>{detail && <Badge tone={tone}>{detail}</Badge>}</div></article>; }

function DashboardPage({ onPage }) { return <><AdminHeader title="Facilities Overview" subtitle="Welcome back, here's what's happening today."><ActionButton secondary><Download />Export Report</ActionButton><ActionButton><Plus />Dispatch Team</ActionButton></AdminHeader><div className="admin-content"><div className="admin-stats"><StatCard label="Total Reports" value="142" detail="+12.5%"/><StatCard label="Pending" value="18" detail="Urgent" tone="red"/><StatCard label="In Progress" value="24" detail="On Track"/><StatCard label="Resolved" value="100" detail="92% Rate"/></div><div className="admin-dashboard-grid"><section><div className="admin-section-heading"><h2>🚨 High Priority Alerts</h2><button onClick={() => onPage("reports")}>View All</button></div><div className="admin-alerts">{[["Broken Elevator - DPT Bldg", "DPT Block B · Level 4 Maintenance Required", "10m ago", "red"], ["Main Pipe Burst", "Science Annex Quad · Immediate flooding risk", "45m ago", "red"], ["Power Outage - West Wing", "Library Sector C · Backup generators engaged", "1h ago", "blue"]].map(([title, copy, ago, tone]) => <article key={title} className={`admin-alert ${tone}`}><span>{tone === "red" ? <XCircle /> : <BellRing />}</span><div><b>{title}</b><p>{copy}</p></div><aside><Badge tone={tone === "red" ? "red" : "blue"}>{tone === "red" ? "Urgent" : "Warning"}</Badge><small>{ago}</small></aside></article>)}</div></section><CategoryChart /></div><MaintenanceTable rows={reportRows.slice(0, 3)} /></div></>; }

function CategoryChart() { const bars = [["Furniture", 66, "#ad0921"], ["Plumbing", 100, "#f78c00"], ["Electrical", 84, "#367cf1"], ["AC/Heat", 50, "#15b985"], ["Cleaning", 42, "#94a3b8"]]; return <section className="admin-card admin-chart"><div className="admin-card-title"><h2>Reports by Category</h2><Badge>Last 7 Days</Badge></div><div className="admin-bars">{bars.map(([label, height, color]) => <div key={label}><span style={{ height: `${height}%`, background: color }} /><b>{label}</b></div>)}</div></section>; }
function MaintenanceTable({ rows }) { return <section className="admin-card admin-table-card"><div className="admin-card-title"><h2>Recent Maintenance Activity</h2><button>Filter by Status</button></div><div className="admin-table-scroll"><table className="admin-table"><thead><tr><th>Report ID</th><th>Facility / Location</th><th>Category</th><th>Reported At</th><th>Status</th><th>Actions</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td><b>{row.id}</b></td><td><b>{row.title}</b><small>{row.place}</small></td><td><Badge tone={row.tone}>{row.category}</Badge></td><td>{row.time}</td><td><Status>{row.status === "Pending" ? "Pending" : row.status}</Status></td><td><button className="admin-link">{row.status === "Pending" ? "Assign" : <Ellipsis />}</button></td></tr>)}</tbody></table></div></section>; }

function ReportsPage() { const [query, setQuery] = useState(""); const filtered = useMemo(() => reportRows.filter((report) => `${report.id} ${report.title} ${report.place}`.toLowerCase().includes(query.toLowerCase())), [query]); return <><AdminHeader title="All Facility Reports" subtitle="Manage and track all maintenance service requests."><ActionButton secondary><Download />Export CSV</ActionButton><ActionButton><Plus />Create Report</ActionButton></AdminHeader><div className="admin-content"><section className="admin-filterbar"><label><Search /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search reports by ID, location or keyword..." /></label><button>All Categories <ChevronDown /></button><button>All Status <ChevronDown /></button><button>All Priorities <ChevronDown /></button><button aria-label="More filters"><SlidersHorizontal /></button></section><section className="admin-card admin-table-card"><div className="admin-table-scroll"><table className="admin-table"><thead><tr><th>Report ID</th><th>Issue & Location</th><th>Category</th><th>Date / Time</th><th>Priority</th><th>Status</th><th>Actions</th></tr></thead><tbody>{filtered.map((row) => <tr key={row.id}><td><b>{row.id}</b></td><td><b>{row.title}</b><small>{row.place}</small></td><td><Badge tone={row.tone}>{row.category}</Badge></td><td>{row.time}</td><td><Badge tone={row.priority === "Urgent" ? "red" : "blue"}>{row.priority}</Badge></td><td><Status>{row.status}</Status></td><td><button className="admin-icon-button"><Ellipsis /></button></td></tr>)}</tbody></table></div><div className="admin-pagination"><span>Showing 1 to {filtered.length} of 142 results</span><div><button disabled>Previous</button><button>Next</button></div></div></section></div></>; }

function TeamPage() { const [filter, setFilter] = useState("All Staff"); return <><AdminHeader title="Team Management" subtitle="Monitor field technician availability and active assignments."><ActionButton secondary><ShieldCheck />Manage Roles</ActionButton><ActionButton><Plus />Add New Member</ActionButton></AdminHeader><div className="admin-content"><section className="admin-filterbar"><label><Search /><input placeholder="Search team members by name or skill..." /></label><div className="admin-segment">{["All Staff", "On Duty", "Offline"].map((item) => <button onClick={() => setFilter(item)} className={filter === item ? "active" : ""} key={item}>{item}</button>)}</div><button aria-label="Filter"><Filter /></button></section><section className="admin-card admin-table-card"><div className="admin-table-scroll"><table className="admin-table admin-team-table"><thead><tr><th>Team Member</th><th>Specialty</th><th>Current Status</th><th>Active Task</th><th>Performance</th><th>Actions</th></tr></thead><tbody>{team.filter((item) => filter === "All Staff" || (filter === "On Duty" ? item[3] === "Active Now" : item[3] === "Offline")).map((item) => <tr key={item[0]}><td><span className="admin-avatar">{item[6]}</span><span><b>{item[0]}</b><small>{item[1]}</small></span></td><td><Wrench className="admin-inline-icon" />{item[2]}</td><td><Badge tone={item[3] === "Active Now" ? "green" : item[3] === "On Break" ? "orange" : "slate"}>{item[3]}</Badge></td><td>{item[4]}</td><td><Star className="admin-star" /> {item[5]}</td><td><button className="admin-icon-button"><CalendarCheck /></button><button className="admin-icon-button"><Ellipsis /></button></td></tr>)}</tbody></table></div><div className="admin-pagination"><span>Showing 5 active members out of 24 total staff</span><div><button>Previous</button><button>Next</button></div></div></section></div></>; }

function AnalyticsPage() { return <><AdminHeader title="Analytics Overview" subtitle="Review performance metrics and maintenance trends."><div className="admin-segment"><button className="active">Last 30 Days</button><button>Quarterly</button><button>Yearly</button></div><ActionButton><Download />Export Report</ActionButton></AdminHeader><div className="admin-content"><div className="admin-stats"><StatCard label="Total Reports" value="1,284" detail="+12.5%"/><StatCard label="Resolved Tasks" value="1,102" detail="+4.2%"/><StatCard label="Avg. Resolution" value="4.2 hrs" detail="-2.1%" tone="red"/><StatCard label="Customer CSAT" value="4.8 / 5" detail="+0.3"/></div><div className="admin-analytics-grid"><TrendChart /><DonutChart /></div><div className="admin-analytics-grid lower"><RecurringIssues /><Technicians /></div></div></>; }
function TrendChart() { const values = [45, 52, 47, 61, 55, 68, 72, 64, 56, 53, 63, 70, 75, 83, 78, 86, 92, 85, 80, 76, 84, 89, 95, 102, 98, 106, 112, 105, 99, 95]; const points = values.map((value, index) => `${(index / (values.length - 1)) * 100},${100 - ((value - 40) / 75) * 100}`).join(" "); return <section className="admin-card admin-trend"><div className="admin-card-title"><h2>Reports Trend (Last 30 Days)</h2><span><i className="admin-dot red"/>Incoming <i className="admin-dot green"/>Resolved</span></div><svg viewBox="0 0 100 100" preserveAspectRatio="none"><polyline points={points} fill="none" stroke="#ad0921" strokeWidth=".7" vectorEffect="non-scaling-stroke"/><polyline points={points} transform="translate(0 5)" fill="none" stroke="#13b981" strokeWidth=".7" vectorEffect="non-scaling-stroke"/></svg></section>; }
function DonutChart() { return <section className="admin-card admin-donut"><h2>Category Distribution</h2><div className="admin-donut-ring"/><ul>{[["Electrical", "35%", "red"], ["Plumbing", "25%", "orange"], ["HVAC", "20%", "blue"], ["Cleaning", "15%", "green"]].map(([label, value, tone]) => <li key={label}><i className={`admin-dot ${tone}`}/>{label}<span>{value}</span></li>)}</ul></section>; }
function RecurringIssues() { return <section className="admin-card admin-list"><div className="admin-card-title"><h2>Recurring Issues</h2><button>View All</button></div>{["Elevator Fault (Block B)", "Water Leakage (Level 2)", "AC Cooling Inefficiency"].map((item, index) => <div key={item}><span>{index + 5}</span><b>{item}<small>{index === 0 ? "Sensor misalignment reported across multiple floors." : "Recurring service issue requires follow-up."}</small></b><em>{12 - index * 4} Instances</em></div>)}</section>; }
function Technicians() { return <section className="admin-card admin-list"><div className="admin-card-title"><h2>Top Tech Performance</h2><button>Leaderboard</button></div>{[["Marcus Sterling", 98, "green"], ["Elena Rodriguez", 92, "red"], ["James Wu", 87, "blue"]].map(([name, score, tone]) => <div className="admin-tech" key={name}><span className="admin-avatar">{name.split(" ").map((part) => part[0]).join("")}</span><b>{name}<small><i className={`admin-progress ${tone}`} style={{ width: `${score}%` }}/></small></b><em>{score}% Efficient</em></div>)}</section>; }

function SettingsPage() { const [settings, setSettings] = useState({ email: true, push: true, sms: false }); return <><AdminHeader title="Settings" subtitle="Manage your account preferences and system configurations."><ActionButton><CheckCircle2 />Save All Changes</ActionButton></AdminHeader><div className="admin-content admin-settings"><section className="admin-card admin-profile"><div className="admin-card-title"><h2><Users />Profile Settings</h2><p>Update your personal information and profile picture.</p></div><div><span className="admin-avatar large">AS</span><label>Full Name<input defaultValue="Admin User" /></label><label>Email Address<input defaultValue="admin@umfixhub.com" /></label></div></section><div className="admin-settings-grid"><ToggleCard title="Notifications" subtitle="Configure how you receive system alerts." values={settings} onChange={(name) => setSettings((value) => ({ ...value, [name]: !value[name] }))}/><section className="admin-card admin-config"><div className="admin-card-title"><h2><SlidersHorizontal />System Config</h2><p>Set your local language and time preferences.</p></div><label>Interface Language<select defaultValue="English (United States)"><option>English (United States)</option><option>Filipino</option></select></label><label>Timezone<select defaultValue="Asia/Manila"><option>Asia/Manila</option><option>UTC</option></select></label></section></div><section className="admin-card admin-security"><div className="admin-card-title"><h2><LockKeyhole />Security</h2><p>Protect your account with advanced security features.</p></div><div><label>Password<input type="password" value="password" readOnly /><small>Change Password</small></label><aside><ShieldCheck /><b>Two-Factor Auth<small>Enhanced account protection</small></b><Badge tone="green">Enabled</Badge><p>Your account is currently protected by 2FA. We'll ask for a code when you log in on a new device.</p><button>Manage 2FA Settings</button></aside></div></section><section className="admin-danger"><div><b>Deactivate Account</b><p>Once you deactivate your account, there is no going back. Please be certain.</p></div><ActionButton>Deactivate</ActionButton></section></div></>; }
function ToggleCard({ title, subtitle, values, onChange }) { return <section className="admin-card admin-toggles"><div className="admin-card-title"><h2><Activity />{title}</h2><p>{subtitle}</p></div>{[["email", "Email Notifications", "Weekly reports and critical alerts"], ["push", "Push Notifications", "Real-time browser updates"], ["sms", "SMS Alerts", "Emergency maintenance triggers"]].map(([key, label, copy]) => <div key={key}><span><b>{label}</b><small>{copy}</small></span><button onClick={() => onChange(key)} className={values[key] ? "on" : ""} aria-label={`Toggle ${label}`}><i /></button></div>)}</section>; }

function userReportRows(reports) {
  if (!reports?.length) return reportRows;
  return reports.map((report) => {
    const lower = `${report.title} ${report.description || ""}`.toLowerCase();
    const category = report.icon === "droplet" || lower.includes("water") || lower.includes("pipe") ? "Plumbing" : report.icon === "snowflake" || lower.includes("air") || lower.includes("ac ") ? "AC/Heat" : report.icon === "bulb" || lower.includes("light") || lower.includes("electr") ? "Electrical" : "Furniture";
    const status = report.status === "resolved" ? "Resolved" : report.status === "in_progress" ? "In Progress" : "Pending";
    return { id: `#REP-${1000 + report.id}`, title: report.title, place: report.location, category, time: report.createdAt || "Today", priority: status === "Pending" ? "Urgent" : "Normal", status, tone: status === "Resolved" ? "green" : status === "In Progress" ? "blue" : "red" };
  });
}

function LiveDashboardPage({ reports, onPage }) {
  const rows = userReportRows(reports);
  const pending = rows.filter((row) => row.status === "Pending").length;
  const active = rows.filter((row) => row.status === "In Progress").length;
  const resolved = rows.filter((row) => row.status === "Resolved").length;
  return <><AdminHeader title="Facilities Overview" subtitle="Live overview of reports submitted by UM FixHub users."><ActionButton secondary><Download />Export Report</ActionButton><ActionButton onClick={() => onPage("team")}><Plus />Dispatch Team</ActionButton></AdminHeader><div className="admin-content"><div className="admin-stats"><StatCard label="Total Reports" value={rows.length} detail="Live data"/><StatCard label="Pending" value={pending} detail={pending ? "Needs attention" : "All clear"} tone="red"/><StatCard label="In Progress" value={active} detail="Active work"/><StatCard label="Resolved" value={resolved} detail={`${rows.length ? Math.round((resolved / rows.length) * 100) : 0}% Rate`}/></div><div className="admin-dashboard-grid"><section><div className="admin-section-heading"><h2>🚨 High Priority Alerts</h2><button onClick={() => onPage("reports")}>View All</button></div><div className="admin-alerts">{rows.filter((row) => row.status !== "Resolved").slice(0, 3).map((row) => <article key={row.id} className={`admin-alert ${row.tone === "blue" ? "blue" : ""}`}><span>{row.tone === "blue" ? <BellRing /> : <XCircle />}</span><div><b>{row.title}</b><p>{row.place}</p></div><aside><Badge tone={row.tone}>{row.priority}</Badge><small>{row.time}</small></aside></article>)}</div></section><CategoryChart /></div><MaintenanceTable rows={rows.slice(0, 5)} /></div></>;
}

function LiveReportsPage({ reports }) {
  const [query, setQuery] = useState("");
  const rows = userReportRows(reports);
  const filtered = rows.filter((report) => `${report.id} ${report.title} ${report.place}`.toLowerCase().includes(query.toLowerCase()));
  return <><AdminHeader title="All Facility Reports" subtitle="Live maintenance reports submitted by UM FixHub users."><ActionButton secondary><Download />Export CSV</ActionButton><ActionButton><Plus />Create Report</ActionButton></AdminHeader><div className="admin-content"><section className="admin-filterbar"><label><Search /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search reports by ID, location or keyword..." /></label><button>All Categories <ChevronDown /></button><button>All Status <ChevronDown /></button><button>All Priorities <ChevronDown /></button><button aria-label="More filters"><SlidersHorizontal /></button></section><section className="admin-card admin-table-card"><div className="admin-table-scroll"><table className="admin-table"><thead><tr><th>Report ID</th><th>Issue & Location</th><th>Category</th><th>Date / Time</th><th>Priority</th><th>Status</th><th>Actions</th></tr></thead><tbody>{filtered.map((row) => <tr key={row.id}><td><b>{row.id}</b></td><td><b>{row.title}</b><small>{row.place}</small></td><td><Badge tone={row.tone}>{row.category}</Badge></td><td>{row.time}</td><td><Badge tone={row.priority === "Urgent" ? "red" : "blue"}>{row.priority}</Badge></td><td><Status>{row.status}</Status></td><td><button className="admin-icon-button"><Ellipsis /></button></td></tr>)}</tbody></table></div><div className="admin-pagination"><span>Showing {filtered.length} of {rows.length} user reports</span><div><button disabled>Previous</button><button>Next</button></div></div></section></div></>;
}

function LiveAnalyticsPage({ reports }) {
  const rows = userReportRows(reports);
  const resolved = rows.filter((row) => row.status === "Resolved").length;
  const active = rows.filter((row) => row.status === "In Progress").length;
  return <><AdminHeader title="Analytics Overview" subtitle="Metrics calculated from reports submitted by users."><div className="admin-segment"><button className="active">Current data</button></div><ActionButton><Download />Export Report</ActionButton></AdminHeader><div className="admin-content"><div className="admin-stats"><StatCard label="Total Reports" value={rows.length} detail="Live"/><StatCard label="Resolved Tasks" value={resolved} detail={`${rows.length ? Math.round((resolved / rows.length) * 100) : 0}% complete`}/><StatCard label="Active Tasks" value={active} detail="In progress" tone="blue"/><StatCard label="Open Reports" value={rows.length - resolved} detail="Needs review" tone="red"/></div><div className="admin-analytics-grid"><TrendChart /><DonutChart /></div><MaintenanceTable rows={rows.slice(0, 5)} /></div></>;
}

const adminUser = { firstName: "UM", lastName: "Admin", initials: "UA", email: "admin@umfixhub.com", studentId: "ADM-001", program: "Facilities Operations", campus: "Matina Campus" };

export default function AdminPanel({ reports, onLogout }) { const [page, setPage] = useState("dashboard"); const pageComponent = { dashboard: <LiveDashboardPage reports={reports} onPage={setPage}/>, reports: <LiveReportsPage reports={reports}/>, team: <TeamPage/>, analytics: <LiveAnalyticsPage reports={reports}/>, settings: <SettingsPage/>, profile: <div className="admin-profile-page"><Profile user={adminUser} reports={reports} onLogout={onLogout} accountType="Administrator" /></div> }[page]; return <div className="admin-app"><AdminSidebar page={page} onPage={setPage}/><main className="admin-main">{pageComponent}</main></div>; }
