import { useEffect, useMemo, useState } from "react";
import Navbar from "./Navbar"; import Footer from "./Footer"; import HeroCard from "./HeroCard"; import RecentReports from "./RecentReports"; import CampusUpdates from "./CampusUpdates"; import ActivityCard from "./ActivityCard"; import EmergencyCard from "./EmergencyCard"; import ReportIssue from "./ReportIssue"; import MyReports from "./MyReports"; import ReportDetail from "./ReportDetail";
import { currentUser, recentReports as initialReports, campusUpdates, activityStats } from "./mockData";
function parseRoute(path) { if (path === "/report-issue") return { name: "report" }; if (path === "/my-reports") return { name: "reports" }; const match = path.match(/^\/my-reports\/(\d+)$/); return match ? { name: "reportDetail", id: Number(match[1]) } : { name: "home" }; }
export default function App() {
 const [route, setRoute] = useState(() => parseRoute(window.location.pathname)); const [reports, setReports] = useState(initialReports);
 useEffect(() => { const listener = () => setRoute(parseRoute(window.location.pathname)); window.addEventListener("popstate", listener); return () => window.removeEventListener("popstate", listener); }, []);
 const navigate = (path) => { window.history.pushState({}, "", path); setRoute(parseRoute(path)); };
 const activeKey = useMemo(() => route.name === "home" ? "home" : route.name === "report" ? "report" : "reports", [route]);
 return <div className="min-h-screen bg-[#f7f9fc] text-slate-900"><Navbar activeKey={activeKey} user={currentUser} onNavigate={navigate}/><main className="max-w-6xl mx-auto px-6 py-10">{route.name === "home" && <div className="grid grid-cols-1 lg:grid-cols-3 gap-6"><div className="lg:col-span-2 space-y-8"><HeroCard onNavigate={navigate}/><RecentReports reports={reports.slice(0,3)} onNavigate={navigate}/></div><div className="space-y-6"><CampusUpdates updates={campusUpdates}/><ActivityCard stats={activityStats}/><EmergencyCard/></div></div>}{route.name === "report" && <ReportIssue onBack={() => navigate("/")} onSubmit={(report) => { setReports((items) => [report, ...items]); navigate("/my-reports"); }}/>} {route.name === "reports" && <MyReports reports={reports} onNavigate={navigate}/>} {route.name === "reportDetail" && <ReportDetail report={reports.find((r) => r.id === route.id)} onBack={() => navigate("/my-reports")} onUpdate={(id, status) => setReports((items) => items.map((item) => item.id === id ? { ...item, status } : item))}/>}</main><Footer/></div>;
}
